export {default as Homepage} from './Homepage'
export {default as About} from './About'
export {default as Footer} from './Footer'
export {default as Skills} from './Skills'
export {default as Contacts} from './Contacts'
